import type { Metadata } from "next";
import { Jost, Dancing_Script } from "next/font/google";
import "./globals.css";
import { AuthProvider } from '../context/AuthProvider';
import Navbar from "@/components/Navbar"; 


const jost = Jost({
  subsets: ["latin"],
  variable: "--font-jost",
});

const dancingScript = Dancing_Script({
  subsets: ["latin"],
  variable: "--font-dancing-script",
});

export const metadata: Metadata = {
  title: "Perfume App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.variable} ${dancingScript.variable}`}>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
