import type { Metadata } from "next";
import { Jost, Dancing_Script } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

// ✅ Load custom fonts
const jost = Jost({
  subsets: ["latin"],
  variable: "--font-jost",
});

const dancingScript = Dancing_Script({
  subsets: ["latin"],
  variable: "--font-dancing-script",
});

export const metadata: Metadata = {
  title: "Perfume App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* ✅ Apply the font variables in body */}
      <body className={`${jost.variable} ${dancingScript.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
